export const episodeMatch = [
  {
    epNum: 1,
    title: "Asteroid Blues",
  },
  {
    epNum: 2,
    title: "Stray Dog Strut",
  },
  {
    epNum: 3,
    title: "Honky Tonk Women",
  },
  {
    epNum: 4,
    title: "Gateway Shuffle",
  },
  {
    epNum: 5,
    title: "Ballad of Fallen Angels",
  },
  {
    epNum: 6,
    title: "Sympathy for the Devil",
  },
  {
    epNum: 7,
    title: "Heavy Metal Queen",
  },
  {
    epNum: 8,
    title: "Waltz for Venus",
  },
  {
    epNum: 9,
    title: "Jamming with Edward",
  },
  {
    epNum: 10,
    title: "Ganymede Elegy",
  },
  {
    epNum: 11,
    title: "Toys in the Attic",
  },
  {
    epNum: 12,
    title: "Jupiter Jazz (Part 1)",
  },
  {
    epNum: 13,
    title: "Jupiter Jazz (Part 2)",
  },
  {
    epNum: 14,
    title: "Bohemian Rhapsody",
  },
  {
    epNum: 15,
    title: "My Funny Valentine",
  },
  {
    epNum: 16,
    title: "Black Dog Serenade",
  },
  {
    epNum: 17,
    title: "Mushroom Samba",
  },
  {
    epNum: 18,
    title: "Speak Like a Child",
  },
  {
    epNum: 19,
    title: "Wild Horses",
  },
  {
    epNum: 20,
    title: "Pierrot le Fou",
  },
  {
    epNum: 21,
    title: "Boogie Woogie Feng Shui",
  },
  {
    epNum: 22,
    title: "Cowboy Funk",
  },
  {
    epNum: 23,
    title: "Brain Scratch",
  },
  {
    epNum: 24,
    title: "Hard Luck Woman",
  },
  {
    epNum: 25,
    title: "The Real Folk Blues (Part 1)",
  },
  {
    epNum: 26,
    title: "The Real Folk Blues (Part 2)",
  },
];

export const characterEpisodesList = [
  {
    id: 1,
    name: "Spiegel, Spike",
    episodes: [...Array(26 + 1).keys()].slice(1),
  },
  {
    id: 2,
    name: "Black, Jet",
    episodes: [...Array(26 + 1).keys()].slice(1),
  },
  {
    id: 3,
    name: "Valentine, Faye",
    episodes: [...Array(23 + 1).keys()].slice(3),
  },
  {
    id: 4,
    name: "Wong Hau Pepelu Tivrusky IV, Edward",
    episodes: [...Array(15 + 1).keys()].slice(9),
  },
  {
    id: 5,
    name: "Ein",
    episodes: [...Array(22 + 1).keys()].slice(2),
  },
  {
    id: 6,
    name: "Vicious",
    episodes: [5, 12, 13, 25, 26],
  },
  {
    id: 7,
    name: "Punch",
    episodes: [2, 3, 9, 12, 14, 17, 22, 23, 25],
  },
  {
    id: 8,
    name: "Judy",
    episodes: [2, 3, 9, 12, 14, 17, 22, 23],
  },
  {
    id: 9,
    name: "Amjad",
    episodes: [9],
  },
  {
    id: 10,
    name: "Laughing Bull",
    episodes: [1, 12, 13, 26],
  },
  {
    id: 11,
    name: "Julia",
    episodes: [13, 25, 26],
  },
  {
    id: 12,
    name: "Solensan, Asimov",
    episodes: [1],
  },
  {
    id: 13,
    name: "Solensan, Keterina",
    episodes: [1],
  },
  {
    id: 14,
    name: "Antonio",
    episodes: [1, 3, 7, 8, 14, 17],
  },
  {
    id: 15,
    name: "Jobim",
    episodes: [1, 3, 7, 14, 17],
  },
  {
    id: 16,
    name: "Carlos",
    episodes: [1, 3, 7, 14, 17],
  },
  {
    id: 17,
    name: "Carlos",
    episodes: [5],
  },
  {
    id: 18,
    name: "Louie",
    episodes: [8],
  },
  {
    id: 19,
    name: "Morgan",
    episodes: [4],
  },
  {
    id: 20,
    name: "Macho",
    episodes: [7],
  },
  {
    id: 21,
    name: "Long, Sou",
    episodes: [12, 25],
  },
  {
    id: 22,
    name: "Huey",
    episodes: [8],
  },
  {
    id: 23,
    name: "Muriel",
    episodes: [7],
  },
  {
    id: 24,
    name: "Bob",
    episodes: [4, 20, 25],
  },
  {
    id: 25,
    name: "Otto",
    episodes: [7],
  },
  {
    id: 26,
    name: "Alisa",
    episodes: [10],
  },
  {
    id: 27,
    name: "Annie",
    episodes: [5],
  },
  {
    id: 28,
    name: "Bonnaro, Rocco",
    episodes: [8],
  },
  {
    id: 29,
    name: "Bonnaro, Stella",
    episodes: [8],
  },
  {
    id: 30,
    name: "Bower, Ted",
    episodes: [22],
    altName: "Teddy Bomber",
  },
  {
    id: 31,
    name: "Calvino, Piccaro",
    episodes: [8],
  },
  {
    id: 32,
    name: "Celonias, Rhint",
    episodes: [10],
  },
  {
    id: 33,
    name: "Coffee",
    episodes: [17],
  },
  {
    id: 34,
    name: "Dewey",
    episodes: [8],
  },
  {
    id: 35,
    name: "Dig",
    episodes: [16],
  },
  {
    id: 36,
    name: "Doctor Baccus",
    episodes: [15],
  },
  {
    id: 37,
    name: "Donnelly",
    episodes: [10],
  },
  {
    id: 38,
    name: "Doohan",
    episodes: [19],
  },
  {
    id: 39,
    name: "Dr. Londes",
    episodes: [23],
  },
  {
    id: 40,
    name: "Eckener, Grencia Mars Elijah Guo",
    episodes: [12, 13],
  },
  {
    id: 41,
    name: "Elroy",
    episodes: [16],
  },
  {
    id: 42,
    name: "Fad",
    episodes: [16],
  },
  {
    id: 43,
    name: "Frank, Jeffly",
    episodes: [17],
  },
  {
    id: 44,
    name: "George",
    episodes: [19],
  },
  {
    id: 45,
    name: "Giraffe",
    episodes: [6],
  },
  {
    id: 46,
    name: "Gordon",
    episodes: [3],
  },
  {
    id: 47,
    name: "Hakim, Abdul",
    episodes: [2],
  },
  {
    id: 48,
    name: "Harman",
    episodes: [19],
  },
  {
    id: 49,
    name: "Harrison",
    episodes: [4],
  },
  {
    id: 50,
    name: "Lütfen, Afedersiniz Hesap",
    episodes: [24],
  },
  {
    id: 51,
    name: "Hex, Chessmaster",
    episodes: [14],
  },
  {
    id: 52,
    name: "Jonathan",
    episodes: [14],
  },
  {
    id: 53,
    name: "Julius",
    episodes: [12],
  },
  {
    id: 54,
    name: "Kellerman, Yuri",
    episodes: [9],
  },
  {
    id: 55,
    name: "Lin",
    episodes: [12, 13],
  },
  {
    id: 56,
    name: "Long, Ping",
    episodes: [12, 25],
  },
  {
    id: 57,
    name: "Long, Wang",
    episodes: [12, 25],
  },
  {
    id: 58,
    name: "MPU",
    episodes: [9],
  },
  {
    id: 59,
    name: "MacIntire",
    episodes: [24],
  },
  {
    id: 60,
    name: "Mad Pierrot",
    episodes: [20],
  },
  {
    id: 61,
    name: "Matsumoto, Whitney Hagas",
    episodes: [15],
  },
  {
    id: 62,
    name: "Miles",
    episodes: [19],
  },
  {
    id: 63,
    name: "Miss Manley",
    episodes: [15],
  },
  {
    id: 64,
    name: "Murdock, Maria",
    episodes: [4],
  },
  {
    id: 65,
    name: "Nero",
    episodes: [16],
  },
  {
    id: 66,
    name: "Panchorero, Baker",
    episodes: [10],
  },
  {
    id: 67,
    name: "Punch’s Mother",
    episodes: [25],
  },
  {
    id: 68,
    name: "Puzi, Meifa",
    episodes: [21],
  },
  {
    id: 69,
    name: "Puzi, Pao",
    episodes: [21],
  },
  {
    id: 70,
    name: "Rather, Mark",
    episodes: [23],
  },
  {
    id: 71,
    name: "Reggie",
    episodes: [19],
  },
  {
    id: 72,
    name: "River, Fatty",
    episodes: [6],
  },
  {
    id: 73,
    name: "Ruth",
    episodes: [19],
  },
  {
    id: 74,
    name: "Sally’s Granddaughter",
    episodes: [24],
  },
  {
    id: 75,
    name: "Shaft",
    episodes: [17],
  },
  {
    id: 76,
    name: "Shin",
    episodes: [25, 26],
  },
  {
    id: 77,
    name: "Sister Clara",
    episodes: [24],
  },
  // {
  //   id: 78,
  //   name: "Spanngen, Ronny",
  //   episodes: [23],
  // },
  {
    id: 79,
    name: "Taxim, Udai",
    episodes: [16],
  },
  {
    id: 80,
    name: "Terpsichore, Victoria",
    episodes: [7],
    altName: "V.T.",
  },
  {
    id: 81,
    name: "Tucan",
    episodes: [16],
  },
  {
    id: 82,
    name: "Von de Oniyate, Andy",
    episodes: [22],
  },
  {
    id: 83,
    name: "Walker, Domino",
    episodes: [17],
  },
  {
    id: 84,
    name: "Wen",
    episodes: [6],
  },
  {
    id: 85,
    name: "Wiles, Tom",
    episodes: [9],
  },
  {
    id: 86,
    name: "Yenrai, Mao",
    episodes: [5],
  },
  {
    id: 87,
    name: "Yung, Sally",
    episodes: [24],
  },
];

// * start here
// use these: https://anidb.net/anime/23#stafflist | https://api.jikan.moe/v4/anime/1/staff | https://www.imdb.com/title/tt0213338/episodes/?ref_=tt_eps | https://docs.api.jikan.moe/#tag/anime/operation/getAnimeStaff
export const staffMatch = [
  {
    name: "Watanabe, Shinichirou",
    direction: [...Array(26 + 1).keys()].slice(1),
    epDirector: [],
    seriesComp: [],
    screenwriter: [17, 21, 24],
    storyboard: [1, 2, 5, 9, 17, 25, 26],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Nobumoto, Keiko",
    direction: [],
    epDirector: [],
    seriesComp: [...Array(26 + 1).keys()].slice(1),
    screenwriter: [1, 3, 6, 12, 13, 15, 22, 25, 26],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Yokote, Michiko",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [2, 5, 7, 8, 11, 16, 17, 24],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Yamaguchi, Ryota",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [3],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Murai, Sadayuki",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [4, 20, 21],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Satou, Dai",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [9, 14, 23],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Inari, Akihiko",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [10, 18, 19],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Takei, Yoshiyuki",
    direction: [],
    epDirector: [1, 4, 8, 12, 18, 20, 23, 26],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Satou, Ikurou",
    direction: [],
    epDirector: [2, 6, 9, 13, 16, 21, 25],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Mori, Kunihiro",
    direction: [],
    epDirector: [3, 7, 11, 15, 17, 22],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Watanabe, Tetsuya",
    direction: [],
    epDirector: [5],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Yamada, Hirokazu",
    direction: [],
    epDirector: [10, 14, 19, 24],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Kawamoto, Toshihiro",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [...Array(26 + 1).keys()].slice(1),
    mechanicalDesigner: [],
    composer: [],
  },
  {
    name: "Kanno, Yoko",
    direction: [],
    epDirector: [],
    seriesComp: [],
    screenwriter: [],
    storyboard: [],
    animDirector: [],
    charDesigner: [],
    mechanicalDesigner: [],
    composer: [...Array(26 + 1).keys()].slice(1),
  },
];
